# Generated by Django 5.2.4 on 2025-08-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_alter_internshipapplication_age'),
        ('departments', '0004_delete_internshipapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waitlist', 'Waitlist'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_departments', to='applications.internshipapplication')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_applications', to='departments.department')),
            ],
        ),
    ]
