# Generated by Django 5.2.4 on 2025-08-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_internshipapplication_age'),
        ('departments', '0004_delete_internshipapplication'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('application', 'department')},
        ),
    ]
