# Generated by Django 5.2.4 on 2025-08-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_department_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='department_additional_info',
            field=models.TextField(default='Not Provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='match',
            name='department_skills',
            field=models.TextField(default='Not Provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='match',
            name='fields_and_counts',
            field=models.JSONField(default='Not Provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='match',
            name='institution_department',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='student_department',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='student_name',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='student_skill',
            field=models.TextField(default='Not Provided', max_length=500),
        ),
    ]
