# Generated by Django 5.2.4 on 2025-08-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_match_department_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='department_additional_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='match',
            name='department_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='match',
            name='fields_and_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='match',
            name='institution_department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='matched_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='student_department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='student_skill',
            field=models.TextField(blank=True, default=''),
        ),
    ]
