# Generated by Django 5.2.4 on 2025-08-09 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_match_department_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fields_and_counts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matched_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
