# Generated by Django 5.2.4 on 2025-08-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_created_at_match_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='department_additional_info',
            new_name='department_potential_project',
        ),
    ]
