# Generated by Django 5.2.5 on 2025-08-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approved', '0005_approved_end_date_approved_start_date'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternProgress',
        ),
        migrations.CreateModel(
            name='ProgressView',
            fields=[
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('approved.approved',),
        ),
    ]
