# Generated by Django 5.2.5 on 2025-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
