# Generated by Django 5.2.4 on 2025-08-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_delete_progress'),
        ('progress', '0004_progress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='status',
        ),
        migrations.AlterField(
            model_name='progress',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.internshipapplication'),
        ),
    ]
