# Generated by Django 5.2.4 on 2025-08-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(default='Not Provided', max_length=100)),
                ('address', models.CharField(default='Not Provided', max_length=200)),
                ('education_level', models.CharField(default='Not Provided', max_length=50)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('passport_id', models.FileField(default='Not Provided', upload_to='passport_ids/')),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(default='Not Provided', max_length=100)),
                ('current_year', models.CharField(default='Not Provided', max_length=10)),
                ('expected_graduation', models.CharField(default='Not Provided', max_length=20)),
                ('skills', models.TextField(blank=True, default='Not Provided')),
                ('interests', models.TextField(default='Not Provided')),
                ('motivation_letter', models.FileField(upload_to='motivation_letters/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('recommendation_letter', models.FileField(upload_to='recommendations/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('application', 'Application Submitted'), ('review', 'Under Review'), ('interview', 'Interview Scheduled'), ('approval', 'Approved')], default='application', max_length=20)),
            ],
        ),
    ]
