# Generated by Django 5.2.4 on 2025-08-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_internshipapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('application', 'Application Submitted'), ('review', 'Under Review'), ('interview', 'Interview Scheduled'), ('approval', 'Approved')], default='pending', max_length=20),
        ),
    ]
