# Generated by Django 5.2.4 on 2025-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_internshipapplication_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='duration',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (4, '4 months'), (5, '5 months'), (6, '6 months'), (7, '7 months'), (8, '8 months'), (9, '9 months'), (10, '10 months'), (11, '11 months'), (12, '12 months')], null=True),
        ),
    ]
