# Generated by Django 5.2.4 on 2025-08-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_internshipapplication_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='duration',
            field=models.CharField(blank=True, choices=[('1 month', '1 month'), ('2 month', '2 months'), ('3 month', '3 months'), ('4 month', '4 months'), ('5 month', '5 months'), ('6 month', '6 months'), ('7 month', '7 months'), ('8 month', '8 months'), ('9 month', '9 months'), ('10 month', '10 months'), ('11 month', '11 months'), ('12 month', '12 months')], max_length=10, null=True),
        ),
    ]
