# Generated by Django 5.2.4 on 2025-08-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
