# Generated by Django 5.2.4 on 2025-08-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_delete_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='institution',
        ),
    ]
