# Generated by Django 5.2.4 on 2025-08-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approved', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
    ]
