# Generated by Django 5.2.4 on 2025-08-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approved', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
