# Generated by Django 5.2.4 on 2025-08-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approved', '0003_approved_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved',
            name='department_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='approved',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
