# Generated by Django 5.2.5 on 2025-08-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approved', '0004_approved_department_name_approved_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approved',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
