# Generated by Django 5.2.5 on 2025-08-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_progress'),
        ('approved', '0005_approved_end_date_approved_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.internshipapplication'),
        ),
    ]
