# Generated by Django 5.2.5 on 2025-08-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approved', '0006_approved_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved',
            name='application',
        ),
    ]
