# Generated by Django 5.2.4 on 2025-08-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approved', '0007_remove_approved_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='approved',
            name='start_date',
        ),
    ]
