# Generated by Django 5.2.4 on 2025-08-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approved', '0008_remove_approved_end_date_remove_approved_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approved',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
