# Generated by Django 5.2.4 on 2025-08-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_match_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='application',
        ),
        migrations.RemoveField(
            model_name='match',
            name='department',
        ),
        migrations.DeleteModel(
            name='Approved',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
