# Generated by Django 5.2.4 on 2025-08-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_remove_match_application_remove_match_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('approval', 'Approval Email'), ('rejection', 'Rejection Email')], max_length=20, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use placeholders like {applicant_name}, {department}')),
            ],
        ),
    ]
