# Generated by Django 5.2.4 on 2025-08-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='report_day',
            field=models.DateField(blank=True, help_text='Date students must come to SSGI', null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Use placeholders like {applicant_name}, {department}, {report_day}'),
        ),
    ]
