# Generated by Django 5.2.4 on 2025-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='fields',
        ),
        migrations.AddField(
            model_name='department',
            name='fields_and_counts',
            field=models.JSONField(default=list),
        ),
    ]
