# Generated by Django 5.2.4 on 2025-08-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_internshipapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
