# Generated by Django 5.2.4 on 2025-08-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_delete_internshipapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='additional_info',
            new_name='potential_project',
        ),
    ]
