# Generated by Django 5.2.4 on 2025-08-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_rename_additional_info_department_potential_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, help_text='Master switch for the Departments portal.')),
                ('open_from', models.DateTimeField(blank=True, help_text='Optional start date/time.', null=True)),
                ('open_until', models.DateTimeField(blank=True, help_text='Optional end date/time.', null=True)),
            ],
            options={
                'verbose_name': 'Departments portal config',
                'verbose_name_plural': 'Departments portal config',
            },
        ),
    ]
