# Generated by Django 5.2.4 on 2025-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_departmentportalconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='department',
            name='email',
        ),
        migrations.RemoveField(
            model_name='department',
            name='phone',
        ),
        migrations.AddField(
            model_name='department',
            name='mentor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
